 name: Test Mint Runner

on:
  workflow_dispatch:  # allows you to trigger manually

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Say hello
        run: |
          echo "Hello from my Linux Mint self-hosted runner!"
          uname -a
          date

